
services:

  postgres:
    container_name: evolution_postgres
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./evolution_postgres:/var/lib/postgresql/data
    env_file:
      - db.env


  api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./evolution_instances:/evolution/instances
      - ./evolution_store:/evolution/store
    env_file:
      - evolution.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8081
    depends_on:
      - postgres
